import json

""" DATA CLASS BUILDERS"""


""" collections.namedtuple """

from collections import namedtuple


coordinate = namedtuple('Coordinate', 'lat lon')
coordinate = namedtuple('Coordinate', ['lat', 'lon'])
# >>> issublass(Coordinate, tuple)
# >>> True

moscow = coordinate(55.756, 37.617)
# >>> moscow
# >>> Coordinate(lat=55.756, lon=37.617)

# >>> moscow == coordinate(lat=55.756, lon=37.617)
# >>> True

City = namedtuple('City', 'name country population coordinates')

tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))

# >>> tokyo.population
# 36.933
# >>> tokyo.coordinates
# (35.689722, 139.691667)


# Named tuple attributes and methods:

# City._fields
# ('name', 'country', 'population', 'location')

Coordinate = namedtuple('Coordinate', 'lat lon')
delhi_data = ('Delhi NCR', 'IN', 21.935, Coordinate(28.613889, 77.208889))

delhi = City._make(delhi_data)
# same as:
delhi = City(*delhi_data) 

delhi_dict = delhi._asdict()
# >>> {'name': 'Delhi NCR', 'country': 'IN', 'population': 21.935, 'coordinates': Coordinate(lat=28.613889, lon=77.208889)}

json.dumps(delhi._asdict())
# >>> '{"name": "Delhi NCR", "country": "IN", "population": 21.935, "location": [28.613889, 77.208889]}'

Coordinate = namedtuple('Coordinate', 'lat lon reference', defaults=['WGS84'])
Coordinate(0, 0)
# >>> Coordinate(lat=0, lon=0, reference='WGS84')
# >>> {'reference': 'WGS84'}


# collections.namedtuple cannot add methods but there is a HACK:

Card = namedtuple('Card', ['rank', 'suit'])

class FrenchDeck:
    ranks = [str(n) for n in range(2, 11)] + list('JQKA')
    suits = 'spades diamond clubs hearts'.split()

    def __init__(self):
        self._cards = [Card(rank, suit) for suit in self.suits for rank in self.ranks]

    def __len__(self):
        return len(self._cards)
        
    def __getitem__(self, position):
        return self._cards[position]
    
suit_values = dict(spades=3, hearts=2, diamond=1, clubs=0)

# Here is a function that ranks cards / method
def spades_high(card):
    rank_value = FrenchDeck.ranks.index(card.rank)
    return rank_value * len(suit_values) + suit_values[card.suit]

# Attach the function to the Card class as a method named overall_rank.
Card.overall_rank = spades_high
lowest_card = Card('2', 'clubs')
highest_card = Card('A', 'spades')
lowest_card.overall_rank()
# >>> 0
highest_card.overall_rank()
# >>> 51




""" typing.NamedTuple"""

import typing
from typing import NamedTuple


Coordinate = typing.NamedTuple('Coordinate',[('lat', float), ('lon', float)])
# >>> issubclass(Coordinate, tuple)
# True
# >>> typing.get_type_hints(Coordinate)
# {'lat': <class 'float'>, 'lon': <class 'float'>}

Coordinate = typing.NamedTuple('Coordinate', lat=float, lon=float)


# In the __init__ method generated by typing.NamedTuple, the fields appear as
# parameters in the same order they appear in the class statement.


class Coords(NamedTuple):
    lat: float
    lon: float

    def __str__(self):
        ns = 'N' if self.lat >= 0 else 'S'
        we = 'E' if self.lon >= 0 else 'W'
        return f'{abs(self.lat):.1f}°{ns}, {abs(self.lon):.1f}°{we}'
    
coords = Coords(26.5, 67.5)

typing.get_type_hints(coords)
# >>> {'lat': <class 'float'>, 'lon': <class 'float'>}




class Coordinate(NamedTuple):
    lat: float
    lon: float
    reference: str = 'WGS84'

Coordinate = NamedTuple('Coordinate', lat=float, lon=float)


# there is no type checking on runtime in type.NamedTuple
trash = Coordinate('NL!', None )

# both types are not float as in class instance fields
# >>> Coordinate(lat='NL!', lon=None)


class DemoNamedTuple(typing.NamedTuple):
    a: int
    b: float = 1.1
    c = 'spam'

# >>> DemoNamedTuple.__annotations__
# {'a': <class 'int'>, 'b': <class 'float'>}

# >>> DemoNamedTuple.a
# _tuplegetter(0, 'Alias for field number 0')
# >>> DemoNamedTuple.b
# _tuplegetter(1, 'Alias for field number 1')
# >>> DemoNamedTuple.c
# 'spam'

# >>> DemoNamedTuple.__doc__
# 'DemoNamedTuple(a, b)'

demo = DemoNamedTuple(8)
# DemoNamedTuple(a=8, b=1.1)


demo_named_tuple = NamedTuple('Demo', a=int, b=float, c='spam')

# in_line_demo = demo_named_tuple(5)
# >>> TypeError: Demo.__new__() missing 2 required positional arguments: 'b' and 'c'
#  !!! CANNOT assing values to isinstance field using this syntax !!!

# ._asdict

Test = NamedTuple('Test', name=str, job=str)

test = Test('bob', 'manager')

print(test)
print(test._asdict())



# pattern matching
import typing

class City(typing.NamedTuple):
    continent: str
    city: str
    country: str

cities = [
 City('Asia', 'Tokyo', 'JP'),
 City('Asia', 'Delhi', 'IN'),
 City('North America', 'Mexico City', 'MX'),
 City('North America', 'New York', 'US'),
 City('South America', 'São Paulo', 'BR'),
]

def match_asian_cities():
    results = []
    for city in cities:
        match city:
            case City(continent='Asia', country=cc):
                results.append(cc)
    print(results)
    
match_asian_cities()





""" @dataclass class builder """


@dataclass
class DemoDataClass:
    a: int
    b: float = 1.1
    c = 'spam'

# >>> DemoDataClass.__annotations__
# {'a': <class 'int'>, 'b': <class 'float'>}
# >>> DemoDataClass.__doc__
# 'DemoDataClass(a: int, b: float = 1.1)'
# >>> DemoDataClass.a
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# AttributeError: type object 'DemoDataClass' has no attribute 'a'
# >>> DemoDataClass.b
# 1.1
# >>> DemoDataClass.c
# 'spam'

dc = DemoDataClass(9)
# >>> dc.a
# 9
# >>> dc.b
# 1.1
# >>> dc.c
# 'spam'

# >>> dc.a = 10
# >>> dc.a
# 10
# >>> dc.b = 1
# >>> dc.b
# 1
# >>> dc.c = 'more spam'
# >>> dc.c
# 'more spam'

# !!! @dataclass builder makes the object mutable !!!

# keyword arguments
# @dataclass(init=True, repr=True, eq=True, order=False,
#  unsafe_hash=False, frozen=False)


# frozen makes obj immutable
@dataclass(frozen=True)
class DemoClass():
    a: int = 1
    b: str = 'a'

fruit = DemoClass(1, 'orange')

# __eq__ set to True by default
# >>> a == b
# >>> True

# in simple class that would take:

class Fruit:
    def __init__(self, quantity=int, color=str) -> None:
        self.quantity = quantity
        self.color = color

    def __eq__(self, other):
        return self.quantity == other.quantity and self.color == other.color


apple = Fruit(1, 'orange')
pear = Fruit(1, 'orange')

# >>> apple == pear
# >>> True



# cannot set mutable value as default 
@dataclass
class ClubMember:
 name: str
 guests: list = []

#  >>> ValueError: mutable default <class 'list'> for field guests is not allowed:
# use default_factory

from typing import ClassVar
# unless
from dataclasses import dataclass, field
@dataclass
class ClubMember:
 name: str
 guests: list = field(default_factory=list)
 athlete: bool = field(default=False, repr=False)

 
@dataclass
class HackerClubMember(ClubMember):
    # annotation like this will make both typechecker and @dataclass "happy"
    all_handles: ClassVar[set[str]] = set()
    handle: str = ''

    def __post_init__(self):
        cls = self.__class__
        if self.handle == '':
            self.handle = self.name.split()[0]
        if self.handle in cls.all_handles:
            msg = f'handle {self.handle!r} already exists.'
            raise ValueError(msg)
        cls.all_handles.add(self.handle)



# init-only variables

from dataclasses import dataclass, InitVar, field
from re import Pattern
import re


# @dataclass
# class C:
#     i: int
#     j: int = None
#     database: InitVar[DatabaseType] = None
 
#     def __post_init__(self, database):
#         if self.j is None and database is not None:
#             self.j = database.lookup('j')
#         c = C(10, database=my_database)
      

@dataclass
class Condition:
    prop1: str
    prop2: str
    prop3: str
    pattern_str: InitVar[str]
    pattern: Pattern = field(init=False)

    def __post_init__(self, pattern_str):
        self.pattern = re.compile(pattern_str)


c = Condition("p1", "p2", "p3", "[a-z]+")